### ISSUE TITLE
问一下 你这个dateset.pkl怎么生成的

### ISSUE THREAD

**Issue by jsjs0827** [ck196/tensorflow-alexnet#1]

**Comment by ck196** [comment]
Sorry, i don't know Chinese.
Do you want to ask about creating dataset.pkl?
You can run function with save=True.
```
def load_data(datafile, num_clss, save=True, save_path='dataset.pkl')
```
- Data file is the list of images file and class. Example:
```
image01.jpg 1
image02.jpg 0
image03.jpg 5
...
```
